name: FakeTAB
version: '${version}'
main: me.zhacked.faketab.FakeTABPlugin
api-version: 1.19
depend: [ ProtocolLib, TAB ]
authors: [ zHacked ]
libraries:
  - com.google.inject:guice:5.1.0
  - org.spongepowered:configurate-yaml:4.1.2
  - com.fasterxml.jackson.core:jackson-databind:2.14.0-rc3